database:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/bukkit
  username: bukkit
  password: ''
  isolation: SERIALIZABLE
  logging: false
  rebuild: false
  enablefilelog: false