name: CivChat
main: civchat.CivChat
version: 1.0
description: Realistic Chat
author: Gu3rr1lla
database: false
commands:
  ccantenna:
    aliases: cca
    description: List the possible reinforcement materials, their strengths, and requirements.
    usage: /ccantenna (or /cca)
  ccnetwork:
    description: Create a network
    usage: /ccnetwork