name: CivChat
main: civchat.CivChat
version: 1.0
description: Realistic Chat
author: Gu3rr1lla
database: false
commands:
  createantenna:
    description: List the possible reinforcement materials, their strengths, and requirements.
    usage: /createantenna <network>
  ccnetwork:
    description: Create a network
    usage: /ccnetwork
  ccsetnetwork:
    description: Set network
    usage: /ccsetnetwork <network-name>
  createphone:
    description: Create phone
    usage: /createphone <network>
  scan:
    description: Scan Networks
    usage: /scan
  connect:
    description: Connect to a network
    usage: /connect <network>